"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_status
"""

right_format = """
$python\
$nodejs\
$cmd_duration\
$time
"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[➜](bold red)"

[cmd_duration]
min_time = 0
format = "[$duration]($style) "

[time]
disabled = false

[directory]
read_only = " 󰌾"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
