[settings]
jobs = 4
env_file = ".env"
python.uv_venv_auto = true
experimental = true

[tools]
atuin = "latest"
bat = "latest"
eza = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
node = "lts"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
uv = "latest"
viteplus = "latest"
yazi = "latest"
zoxide = "latest"
